// AUTO-GENERATED by scripts/sync-product-images.py — do not edit by hand.
// Re-run that script after adding/removing images in the CDN PRODUCTS folder.

export const PRODUCT_IMAGES: Record<string, string[]> = {
  "technical-textiles": [
    "/images/products/technical-textiles/technical-textiles-01.jpg",
    "/images/products/technical-textiles/technical-textiles-02.jpg",
    "/images/products/technical-textiles/technical-textiles-03.jpg",
    "/images/products/technical-textiles/technical-textiles-04.jpg",
    "/images/products/technical-textiles/technical-textiles-05.jpg",
    "/images/products/technical-textiles/technical-textiles-06.jpg",
    "/images/products/technical-textiles/technical-textiles-07.jpg",
  ],
  "engineered-fashion": [
    "/images/products/engineered-fashion/engineered-fashion-01.jpg",
    "/images/products/engineered-fashion/engineered-fashion-02.jpg",
    "/images/products/engineered-fashion/engineered-fashion-03.jpg",
    "/images/products/engineered-fashion/engineered-fashion-04.jpg",
    "/images/products/engineered-fashion/engineered-fashion-05.jpg",
    "/images/products/engineered-fashion/engineered-fashion-06.jpg",
    "/images/products/engineered-fashion/engineered-fashion-07.jpg",
    "/images/products/engineered-fashion/engineered-fashion-08.jpg",
  ],
  "yarn": [
    "/images/products/yarn/yarn-01.jpg",
    "/images/products/yarn/yarn-02.jpg",
    "/images/products/yarn/yarn-03.jpg",
    "/images/products/yarn/yarn-04.jpg",
    "/images/products/yarn/yarn-05.jpg",
  ],
  "fiber": [
    "/images/products/fiber/fiber-01.jpg",
    "/images/products/fiber/fiber-02.jpg",
    "/images/products/fiber/fiber-03.jpg",
  ],
};
